### ISSUE TITLE
Zooming in/out diagram triggers "Unhandled Error" message in browser

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/synapse#31] opened 2022-04-17 15:09 UTC
https://user-images.githubusercontent.com/119422/163720527-15576eb2-9548-4b6e-825b-42b6bfdc5c28.mp4

**Comment by tsurdilo** [comment] 2022-04-17 15:20
Noticed that this message can also be sometimes triggered when clicking the "Info" button as well. 
Just fyi this also happens in Synapse.Dashboard

**Comment by JBBianchi** [comment] 2022-04-19 11:45
I'm not able to reproduce the error. @tsurdilo could you please open up the dev console and get the complete error message form there please?

The one on the info button is probably different, if you can start a new issue with the details new time you get it, it would be great, thanks :)

**Comment by JBBianchi** [comment] 2022-04-27 10:15
@tsurdilo any update ?

**Comment by tsurdilo** [comment] 2022-05-02 03:08
@JBBianchi with latest update i get it on web ui load:

<img width="537" alt="Screen Shot 2022-05-01 at 11 07 57 PM" src="https://user-images.githubusercontent.com/119422/166179699-4c64ca5b-19a2-4dba-b931-5b678d2db9fa.png">

**Comment by JBBianchi** [comment] 2022-05-02 13:52
> @JBBianchi with latest update i get it on web ui load. hope this helps:
> 
> <img alt="Screen Shot 2022-05-01 at 11 07 57 PM" width="537" src="https://user-images.githubusercontent.com/119422/166179699-4c64ca5b-19a2-4dba-b931-5b678d2db9fa.png">

I think this is related to #49

**Comment by JBBianchi** [comment] 2022-05-13 10:30
I'll close this issue because it's too generic and the error shown above should be fixed now.

**Closed by JBBianchi** 2022-05-13 10:30 UTC
Labels: bug, dashboard, priority: medium, weight: 1
