### ISSUE TITLE
Synape.Integration - nuget package usage

### ISSUE THREAD

**Issue by rmanjusha** [serverlessworkflow/synapse#363] opened 2024-04-15 20:55 UTC
Hello, 

**What is the question**:

I referred serverless workflow sdk .net  documentation on building workflow programmatically using C#.  Few questions on Synape.Integration  package usage :

1. Is there a base class for creating functions instead of using inline functions?
2.  I am looking for way to define shared functions with C# (custom function type using .net)  and I want the workflow control flow to be defined in JSON.  My API will be reading workflow definition JSON and need run the workflow definition. Please advise.

**Comment by cdavernas** [comment] 2024-05-26 13:01
Hello @rmanjusha!

I'm closing this as a dupe of #364, in which you can hopefully find the answers to your questions ;)

**Closed by cdavernas** 2024-05-26 13:01 UTC
Labels: duplicate
