### ISSUE TITLE
Win32Exception thrown when invoking `JQ` with a very large command on Windows

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#81] opened 2022-05-10 14:59 UTC
**What happened**:

When executing an action that returns a very large payload, the worker application will fault by throwing the following exception:

```
System.ComponentModel.Win32Exception (206): An error occurred trying to start process 'cmd.exe' with working directory '[DIRECTORY]'. The filename or extension is too long.
```

**What you expected to happen**:

In case the input data, the filter expression and the variables are too long, they should be written to separate, temporary files, thus avoiding the path's length restriction

**How to reproduce it**:

Run an instance of a workflow that defines an action which will return a large JSON payload

**Anything else we need to know?**:

Only seems to occur on Windows

**Environment**:

Windows 11 PRO x64

**Comment by JBBianchi** [comment] 2022-05-10 15:05
duplicate of #74

**Closed** 2022-05-11 11:55 UTC
Labels: bug, duplicate, priority: high, weight: 2, worker, windows
