### ISSUE TITLE
System.NullReferenceException: Failed to find an action that matches the metadata specified by the activity

### ISSUE THREAD

**Issue by jaliyaudagedara** [serverlessworkflow/synapse#340] opened 2023-03-07 04:09 UTC
I am evaluating Serverless workflows with Synapse for one of our workflow requirements.

I am running a container of Synapse `latest` locally on Docker.

I have the following simple workflow.

```json
{
  "id": "eventbasedgreeting",
  "name": "Event Based Greeting Workflow",
  "description": "Event Based Greeting",
  "version": "1.0.3",
  "specVersion": "0.8",
  "events": [
    {
      "name": "GreetingEvent",
      "source": "https://demo.synpase.com",
      "type": "com.synapse.demo/greet-received"
    }
  ],
  "functions": [
    {
      "name": "greetingFunction",
      "operation": "https://jm1v3w2c-44386.aue.devtunnels.ms/swagger/v1/swagger.json#GetGreeting",
      "type": "rest"
    }
  ],
  "start": "Greet",
  "states": [
    {
      "name": "Greet",
      "type": "event",
      "onEvents": [
        {
          "actions": [
            {
              "functionRef": {
                "refName": "greetingFunction",
                "arguments": {
                  "name": "${ .greet.name }"
                }
              }
            }
          ],
          "eventRefs": [
            "GreetingEvent"
          ],
          "eventDataFilter": {
            "data": "${ .greet }",
            "toStateData": "${ .greet }"
          }
        }
      ],
      "stateDataFilter": {
        "output": "${ .payload.greeting }"
      },
      "end": true
    }
  ]
}
```
I am publishing an event as follows,
```curl
curl --location 'http://localhost:42286' \
--header 'Content-Type: application/cloudevents+json' \
--data '{
    "id": "8b080838-2976-493d-897f-07803944f4d5",
    "specversion": "1.0",
    "source": "https://demo.synpase.com",
    "type": "com.synapse.demo/greet-received",
    "datacontenttype": "application/json",
    "data": {
        "greet": {
            "name": "John"
        }
    }
}'
```
From the UI, I can see the workflow is getting triggered and getting faulted with the following message:
```
{
  "code": "NullReference",
  "message": "Failed to find an action that matches the metadata specified by the activity with id 'de44aeb2-b392-4969-8048-bbf697fe541a'"
}
```

Then debugged `Synpase.Server` and it logs as follows:
```
[02:37:36] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
      Initializing the runtime context for workflow instance with id 'eventbasedgreeting-tzsipbrwn0qicdug5mppq'...
[02:37:36] info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
[02:37:36] info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
[02:37:36] info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
[02:37:36] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
      Retrieving definition of workflow with id 'eventbasedgreeting:1.0.0'...
[02:37:37] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
      Runtime context initialized
[02:37:37] info: Synapse.Worker.Services.WorkflowRuntime[0]
      Starting the workflow's execution...
[02:37:38] info: Synapse.Worker.Services.Processors.EventStateProcessor[0]
      Initializing activity '968e7697-e083-4bab-a7ae-3c70e5e155a8' (type: 'State')...
[02:37:38] info: Synapse.Worker.Services.Processors.EventStateProcessor[0]
      Activity '968e7697-e083-4bab-a7ae-3c70e5e155a8' (type: 'State') initialized
[02:37:38] info: Synapse.Worker.Services.Processors.EventStateProcessor[0]
      Starting/resuming activity '968e7697-e083-4bab-a7ae-3c70e5e155a8' (type: 'State')...
[02:37:38] info: Synapse.Worker.Services.Processors.EventStateTriggerProcessor[0]
      Initializing activity '4726e3d9-4eec-4c16-95f7-15e0271a76b8' (type: 'EventTrigger')...
[02:37:38] info: Synapse.Worker.Services.Processors.EventStateTriggerProcessor[0]
      Activity '4726e3d9-4eec-4c16-95f7-15e0271a76b8' (type: 'EventTrigger') initialized
[02:37:38] info: Synapse.Worker.Services.Processors.EventStateTriggerProcessor[0]
      Starting/resuming activity '4726e3d9-4eec-4c16-95f7-15e0271a76b8' (type: 'EventTrigger')...
[02:37:38] info: Synapse.Worker.Services.Processors.ConsumeEventProcessor[0]
      Initializing activity 'b93f31df-bf6d-40d3-bbed-149f08b0c7ca' (type: 'ConsumeEvent')...
[02:37:38] info: Synapse.Worker.Services.Processors.ConsumeEventProcessor[0]
      Activity 'b93f31df-bf6d-40d3-bbed-149f08b0c7ca' (type: 'ConsumeEvent') initialized
[02:37:38] info: Synapse.Worker.Services.Processors.ConsumeEventProcessor[0]
      Starting/resuming activity 'b93f31df-bf6d-40d3-bbed-149f08b0c7ca' (type: 'ConsumeEvent')...
[02:37:38] info: Synapse.Worker.Services.Processors.ConsumeEventProcessor[0]
      Activity 'b93f31df-bf6d-40d3-bbed-149f08b0c7ca' (type: 'ConsumeEvent') completed
[02:37:39] fail: Synapse.Worker.Services.WorkflowActivityProcessorFactory[0]
      An error occured while creating a new processor for the activity with id 'de44aeb2-b392-4969-8048-bbf697fe541a': System.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id 'de44aeb2-b392-4969-8048-bbf697fe541a'
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 125
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 72
[02:37:39] warn: Synapse.Worker.Services.Processors.EventStateTriggerProcessor[0]
      An error occured while executing the activity '4726e3d9-4eec-4c16-95f7-15e0271a76b8' (type: 'EventTrigger')/r/nDetails:/r/nSystem.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id 'de44aeb2-b392-4969-8048-bbf697fe541a'
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 125
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 72
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Synapse.Worker.Services.IWorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 320
         at Synapse.Worker.Services.WorkflowActivityProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 196
         at Synapse.Worker.Services.Processors.EventStateTriggerProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs:line 69
         at Synapse.Worker.Services.Processors.EventStateTriggerProcessor.OnEventResultAsync(ConsumeEventProcessor processor, V1WorkflowActivityCompletedIntegrationEvent e, CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs:line 214
         at Synapse.Worker.Services.Processors.EventStateTriggerProcessor.<>c__DisplayClass10_1.<<CreateProcessorFor>b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs:line 76
[02:37:39] warn: Synapse.Worker.Services.Processors.EventStateProcessor[0]
      An error occured while executing the activity '968e7697-e083-4bab-a7ae-3c70e5e155a8' (type: 'State')/r/nDetails:/r/nSystem.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id 'de44aeb2-b392-4969-8048-bbf697fe541a'
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 125
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 72
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Synapse.Worker.Services.IWorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 320
         at Synapse.Worker.Services.WorkflowActivityProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 196
         at Synapse.Worker.Services.Processors.EventStateTriggerProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs:line 69
         at Synapse.Worker.Services.Processors.EventStateTriggerProcessor.OnEventResultAsync(ConsumeEventProcessor processor, V1WorkflowActivityCompletedIntegrationEvent e, CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs:line 214
         at Synapse.Worker.Services.Processors.EventStateTriggerProcessor.<>c__DisplayClass10_1.<<CreateProcessorFor>b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs:line 76
[02:37:39] warn: Synapse.Worker.Services.WorkflowRuntime[0]
      An error occured while executing the workflow instance: System.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id 'de44aeb2-b392-4969-8048-bbf697fe541a'
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 125
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 72
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Synapse.Worker.Services.IWorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 320
         at Synapse.Worker.Services.WorkflowActivityProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 196
         at Synapse.Worker.Services.Processors.EventStateTriggerProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs:line 69
         at Synapse.Worker.Services.Processors.EventStateTriggerProcessor.OnEventResultAsync(ConsumeEventProcessor processor, V1WorkflowActivityCompletedIntegrationEvent e, CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs:line 214
         at Synapse.Worker.Services.Processors.EventStateTriggerProcessor.<>c__DisplayClass10_1.<<CreateProcessorFor>b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/Processors/EventStateTriggerProcessor.cs:line 76
[02:37:39] info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```
![image](https://user-images.githubusercontent.com/5653381/223318375-b072bcac-9bcd-4a2d-aafd-4e1db23e2b5c.png)

Any help is appreciated.

**Comment by JBBianchi** [comment] 2023-03-07 09:54
Probably a duplicate of #263, can you try again by providing a name to your action?

**Comment by jaliyaudagedara** [comment] 2023-03-07 16:41
just tried and that was it. Thanks!

Spent a day on that :( :( Should we update the [action definition specification](https://github.com/serverlessworkflow/specification/blob/main/specification.md#Action-Definition)?

![image](https://user-images.githubusercontent.com/5653381/223489156-4a53c296-3df3-4dca-85d5-8d98f4ad2827.png)

**Comment by JBBianchi** [comment] 2023-03-07 18:10
You can maybe reply to https://github.com/serverlessworkflow/specification/issues/685 ? Or open another issue, idk... I think maintainers agreed but it never made its way to the spec.

**Closed by JBBianchi** 2023-03-07 18:10 UTC

**Comment by jaliyaudagedara** [comment] 2023-03-09 07:13
All good :)

Just left a comment!
